"""
Django settings for memoryvault_project project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Loads a local .env file if present (for local development). In production
# (Render), real environment variables are injected by the platform and this
# is a no-op since there is no .env file deployed.
load_dotenv(BASE_DIR / '.env')


def _get_bool_env(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in ('true', '1', 'yes', 'on')


# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False (secure by default) — must be explicitly enabled for
# local development via DEBUG=True in .env.
DEBUG = _get_bool_env('DEBUG', default=False)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        # Convenience fallback so `runserver` works out of the box locally
        # even without a .env file. Never used when DEBUG=False.
        SECRET_KEY = 'django-insecure-local-dev-only-do-not-use-in-production'
    else:
        raise ImproperlyConfigured(
            'SECRET_KEY environment variable must be set when DEBUG=False.'
        )

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if host.strip()
]

# Needed for CSRF checks to pass on HTTPS deployments (e.g. Render's
# *.onrender.com domain, or a custom domain) — Django requires the scheme.
CSRF_TRUSTED_ORIGINS = [
    f'https://{host}'
    for host in ALLOWED_HOSTS
    if host not in ('localhost', '127.0.0.1')
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'vault',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'memoryvault_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'memoryvault_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# If DATABASE_URL is set (Render provides this automatically when a
# Postgres instance is attached), use it. Otherwise fall back to local
# SQLite for development.
import dj_database_url

DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
            ssl_require=not DEBUG,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Per-app static dirs (e.g. vault/static/) are auto-discovered via APP_DIRS
# staticfiles finder. STATIC_ROOT is where `collectstatic` gathers everything
# for production deployment (not used directly by the dev server).
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise: serves compressed, cache-busted static files directly from
# gunicorn without needing a separate static file host (nginx/S3/CDN).
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_URL = '/auth/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/auth/login/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Security
# https://docs.djangoproject.com/en/5.2/topics/security/
# These are only enforced when DEBUG=False so local development over plain
# HTTP on localhost keeps working without extra setup.

SECURE_SSL_REDIRECT = _get_bool_env('SECURE_SSL_REDIRECT', default=not DEBUG)

# Render terminates TLS at its edge proxy and forwards plain HTTP internally,
# so Django needs this header to know the original request was HTTPS
# (otherwise SECURE_SSL_REDIRECT causes a redirect loop).
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

# NOTE: CSRF_COOKIE_HTTPONLY is intentionally left at Django's default
# (False). Several pages (dashboard.html, ai_assistant.html,
# productivity.html) read the csrftoken cookie via JS to attach the
# X-CSRFToken header on fetch() calls; making the cookie HttpOnly would
# break those AJAX actions.

SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# HSTS: start at 1 week rather than the commonly-recommended 1 year. HSTS
# is sticky in the browser once sent, so ramp this up manually once HTTPS
# is confirmed stable in production, rather than risking users being
# locked out of the site over HTTP for a full year from day one.
SECURE_HSTS_SECONDS = 0 if DEBUG else 604800  # 7 days
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG


# Logging
# https://docs.djangoproject.com/en/5.2/topics/logging/
# Logs to stdout/stderr so the platform (Render) captures and aggregates
# them — no log files are written to disk.

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'django.request': {
            # Ensures unhandled 500 errors are always logged with their
            # traceback, even though DEBUG=False suppresses the on-screen
            # error page.
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'vault': {
            'handlers': ['console'],
            'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
    },
}
