# Generated by Django 5.2.15 on 2026-07-02 02:03

import vault.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_profile_email_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarevent',
            options={'ordering': ['date', 'time']},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['due_date', 'kanban_order', '-created_at']},
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='memory',
            name='category',
            field=models.CharField(blank=True, choices=[('Work', 'Work'), ('Personal', 'Personal'), ('Ideas', 'Ideas'), ('Learning', 'Learning'), ('Health', 'Health'), ('Travel', 'Travel'), ('Finance', 'Finance'), ('Other', 'Other')], default='Personal', max_length=20),
        ),
        migrations.AddField(
            model_name='memory',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memory',
            name='related_memories',
            field=models.ManyToManyField(blank=True, to='vault.memory'),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#7C3AED', max_length=7),
        ),
        migrations.AddField(
            model_name='task',
            name='kanban_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='memory',
            name='mood',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('digest', 'Daily Digest'), ('insight', 'AI Insight'), ('system', 'System')], default='system', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ai_preferences',
            field=models.JSONField(default=vault.models.get_default_ai_prefs),
        ),
        migrations.AlterField(
            model_name='profile',
            name='appearance_preferences',
            field=models.JSONField(default=vault.models.get_default_appearance_prefs),
        ),
        migrations.AlterField(
            model_name='profile',
            name='notification_preferences',
            field=models.JSONField(default=vault.models.get_default_notif_prefs),
        ),
    ]
