# Generated by Django 6.0.6 on 2026-07-03 06:38

import vault.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0004_alter_collection_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accessibility_preferences',
            field=models.JSONField(default=vault.models.get_default_accessibility_prefs),
        ),
        migrations.AddField(
            model_name='profile',
            name='privacy_preferences',
            field=models.JSONField(default=vault.models.get_default_privacy_prefs),
        ),
    ]
